#!/bin/bash

# This is a thin wrapper around ion-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using ion-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_IOND

# Grab the value of $REAL_IONCLI which may be ion-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_IONCLI}" "$@" | sed 's/\r//'
